plugins {
    id 'com.android.application'
}

android {
    namespace 'com.humanpartner'
    compileSdk 35

    defaultConfig {
        applicationId 'com.humanpartner'
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName '0.1.4'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }
}
